### ISSUE TITLE
Seekbar_FEATURES ERROR

### ISSUE THREAD

**Issue by hayate001** [LGLTeam/Android-Mod-Menu#11]
hi sir , when i set seekbar features it always start from 0 _ 100 like exam : "SeekBar_SPEED_1_100"
it not start from 1 - > 100 , always start from 0 - 100 . please fix it sir !

**Comment by hayate001** [comment]
@LGLTeam

**Comment by LGLTeam** [comment]
Fixed, thanks

**Comment by hayate001** [comment]
> Fixed, thanks

THANK FOR HARD WORK SIR , BUT SEEMLIKE IT NOT FIXED , WHEN I TRY TO SET AGAIN "SeekBar_SPEED_1_100" , AND OPEN MENU IT SHOW START FROM 1 -> 100 , BUT WHEN I SLIDE THE BAR IT CAN BE CHANGE TO 0 , HOPE U CAN FIX IT . THANK YOU FOR HARD WORK

**Comment by hayate001** [comment]
> Fixed, thanks

IN OLD LGL MENU WHEN I SET "SeekBar_SPEED_1_100" IT ALWAYS START FROM 1 -> 100 AND WHEN I SLIDE THE SEEKBAR IT NEVER GO TO 0 , BUT WITH NEW LGL TEAM MENU , WHEN I SLIDE THE SEEKBAR IT GO TO 0

**Comment by hayate001** [comment]
> Fixed, thanks

AND HERE IS SCREENSHOOT
![Untitled](https://user-images.githubusercontent.com/56855590/96147325-678c6380-0f31-11eb-9b13-452c1cb388fe.png)
AND HERE IS MY CODE 
    const char *features[] = 
	{
            OBFUSCATE("SeekBar_SPEED MULTIPLE_1_100"),
            OBFUSCATE("SeekBar_MOVEMENT MULTIPLE_1_100"),
    };

**Comment by LGLTeam** [comment]
Issue reopened. I will fix it later
Please do not use caps lock. Otherwise, this issue will be permanently locked

**Comment by LGLTeam** [comment]
Fixed again. Please try and feedback

**Comment by hayate001** [comment]
> Fixed again. Please try and feedback

Thank you sir now it be fixed . Tks U So Much !!!
Ahh can you re-add " const char *libName = "libName.so" back ?

**Comment by LGLTeam** [comment]
> > Fixed again. Please try and feedback
> 
> Thank you sir now it be fixed . Tks U So Much !!!
> Ahh can you re-add " const char *libName = "libName.so" back ?

You can do it yourself or just do `libName = OBFUSCATE("libOtherLib.so");` to apply globally
